[package]
name = "cargo-cosmopolitan"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
description = "Build no_std Rust programs as Cosmopolitan Actually Portable Executables."
repository = "https://github.com/andrewchambers/cargo-cosmopolitan"
readme = "README.md"
publish = false

[dependencies]
serde_json = "1"

[workspace]
